# Spin up Thor and Odin with Docker Compose
services:
  thor:
    image: thor:latest
    build: ./thor
    platform: linux/amd64
    container_name: thor
    ports:
      - "6000:6000"
    environment:
      - THOR_ENV=production
      - THOR_PORT=6000
    volumes:
      - ./thor_data:/data/thor
    extra_hosts:
      - "host.docker.internal:host-gateway"

  odin:
    image: odin:latest
    build: ./odin
    platform: linux
    container_name: odin
    ports:
      - "4000:4000"
    environment:
      - ODIN_ENV=production
      - ODIN_PORT=4000
    volumes:
      - ./odin_data:/data/odin

  rabbit:
    image: rabbitmq:latest
    platform: linux
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  carla:
    image: carlasim/carla:0.9.15
    privileged: true
    platform: linux
    container_name: carla
    ports:
      - "2000:2000"
      - "2001:2001"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    environment:
      - CARLA_ENV=production
      - CARLA_PORT=2000
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XDG_RUNTIME_DIR=/tmp/runtime
      - SDL_VIDEODRIVER=x11
      - DISPLAY=$DISPLAY
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, graphics, display]
    volumes:
      - ./carla_data:/data/carla
      - ${SCENARIO_RUNNER_ROOT}/logs:/logs
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /usr/share/vulkan/icd.d:/usr/share/vulkan/icd.d
    command: >
      ./CarlaUE4.sh -quality-level=epic -carla-rpc-port=2000 -nosound

volumes:
  rabbit_data:
  carla_data:
