# Spin up Thor and Odin with Docker Compose
services:
  thor:
    image: thor:latest
    build: ./thor
    container_name: thor
    network_mode: host
    environment:
      - THOR_ENV=production
      - THOR_PORT=5000
    volumes:
      - ./thor_data:/data/thor

  odin:
    image: odin:latest
    build: ./odin
    container_name: odin
    network_mode: host
    environment:
      - ODIN_ENV=production
      - ODIN_PORT=4000
    volumes:
      - ./odin_data:/data/odin

  rabbit:
    image: rabbitmq:latest
    network_mode: host
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

volumes:
  rabbit_data:
