// Script to save a run of a scenario with enhancements from an LLM.

// Assume relevant env vars are set
import { env_var_load } from "std/env"



const scenario_root = env_var_load("SCENARIO_RUNNER_ROOT")
const hefe_root = env_var_load("HEFE_ROOT")
const file_name = "route_obstacles.py"
const scenario_name = "Accident_1" // Change as needed

const input_name="{scenario_root}/srunner/scenarios/{file_name}"
const output_folder="{hefe_root}/odin/experiments/data/{scenario_name}-mod-{date()}"

const log_dir="{scenario_root}/logs"

$mkdir -p {output_folder}$ failed {
    print("Folder already exists or could not be created.")
}

trust $cd {output_folder}$

// Save what code was used
trust $cp {input_name} {file_name}$

trust $cp ¥{log_dir}/{scenario_name}* .$

output_folder="{hefe_root}/odin/experiments/data/{file_name}"